-- ZERO-COST FUNCTIONAL PILOT
-- Run this in a Snowflake trial account that has NO payment method attached.
-- Trial accounts do not support Openflow. These rows simulate Openflow's target shape.

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE RESOURCE MONITOR FLOWPROOF_PILOT_MONITOR
  WITH CREDIT_QUOTA = 1
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 50 PERCENT DO NOTIFY
    ON 75 PERCENT DO SUSPEND
    ON 90 PERCENT DO SUSPEND_IMMEDIATE;

CREATE OR REPLACE WAREHOUSE FLOWPROOF_PILOT_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  STATEMENT_TIMEOUT_IN_SECONDS = 120
  COMMENT = 'Short-lived FlowProof free-trial pilot';

ALTER WAREHOUSE FLOWPROOF_PILOT_WH
  SET RESOURCE_MONITOR = FLOWPROOF_PILOT_MONITOR;

CREATE DATABASE IF NOT EXISTS FLOWPROOF_PILOT;
CREATE SCHEMA IF NOT EXISTS FLOWPROOF_PILOT.RAW;

CREATE OR REPLACE TABLE FLOWPROOF_PILOT.RAW.ORDERS (
  id NUMBER(38, 0) NOT NULL,
  status VARCHAR(32) NOT NULL,
  amount NUMBER(12, 2) NOT NULL,
  -- PostgreSQL TIMESTAMPTZ maps to TIMESTAMP_LTZ in Snowflake Openflow.
  updated_at TIMESTAMP_LTZ NOT NULL,
  _SNOWFLAKE_INSERTED_AT TIMESTAMP_NTZ NOT NULL,
  _SNOWFLAKE_UPDATED_AT TIMESTAMP_NTZ NOT NULL,
  _SNOWFLAKE_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (id)
);

INSERT INTO FLOWPROOF_PILOT.RAW.ORDERS
  (id, status, amount, updated_at, _SNOWFLAKE_INSERTED_AT, _SNOWFLAKE_UPDATED_AT, _SNOWFLAKE_DELETED)
VALUES
  (1, 'created', 25.00, '2026-08-22T18:00:00Z', '2026-08-22T18:00:30', '2026-08-22T18:00:30', FALSE),
  (2, 'paid', 100.50, '2026-08-22T18:01:00Z', '2026-08-22T18:01:30', '2026-08-22T18:01:30', FALSE),
  (3, 'shipped', 75.25, '2026-08-22T18:02:00Z', '2026-08-22T18:02:30', '2026-08-22T18:02:30', FALSE),
  (4, 'cancelled', 10.00, '2026-08-22T18:03:00Z', '2026-08-22T18:03:30', '2026-08-22T18:03:30', FALSE),
  (5, 'paid', 250.00, '2026-08-22T18:04:00Z', '2026-08-22T18:04:30', '2026-08-22T18:04:30', FALSE);

CREATE ROLE IF NOT EXISTS FLOWPROOF_READER;

-- Replace this password before executing the statement.
CREATE USER IF NOT EXISTS FLOWPROOF_READER
  PASSWORD = 'REPLACE_WITH_A_STRONG_UNIQUE_PASSWORD'
  DEFAULT_ROLE = FLOWPROOF_READER
  DEFAULT_WAREHOUSE = FLOWPROOF_PILOT_WH
  DEFAULT_NAMESPACE = FLOWPROOF_PILOT.RAW
  MUST_CHANGE_PASSWORD = FALSE;

ALTER USER FLOWPROOF_READER SET TIMEZONE = 'UTC';
GRANT ROLE FLOWPROOF_READER TO USER FLOWPROOF_READER;
GRANT USAGE ON WAREHOUSE FLOWPROOF_PILOT_WH TO ROLE FLOWPROOF_READER;
GRANT USAGE ON DATABASE FLOWPROOF_PILOT TO ROLE FLOWPROOF_READER;
GRANT USAGE ON SCHEMA FLOWPROOF_PILOT.RAW TO ROLE FLOWPROOF_READER;
GRANT SELECT ON TABLE FLOWPROOF_PILOT.RAW.ORDERS TO ROLE FLOWPROOF_READER;

ALTER WAREHOUSE FLOWPROOF_PILOT_WH SUSPEND;
