-- TEST-ONLY NATIVE WAL RELAY
-- This creates a dedicated writer identity and ledger for FlowProof's failure tests.
-- It models selected documented Openflow boundaries; it does not run or validate Openflow.

USE ROLE ACCOUNTADMIN;
USE DATABASE FLOWPROOF_PILOT;
USE SCHEMA RAW;

CREATE ROLE IF NOT EXISTS FLOWPROOF_RELAY_ROLE;

-- Replace the password every time before running this script.
CREATE USER IF NOT EXISTS FLOWPROOF_RELAY
  DEFAULT_ROLE = FLOWPROOF_RELAY_ROLE
  DEFAULT_WAREHOUSE = FLOWPROOF_PILOT_WH
  DEFAULT_NAMESPACE = FLOWPROOF_PILOT.RAW
  MUST_CHANGE_PASSWORD = FALSE;

ALTER USER FLOWPROOF_RELAY
  SET PASSWORD = 'REPLACE_WITH_A_DIFFERENT_STRONG_UNIQUE_PASSWORD'
      TIMEZONE = 'UTC';

GRANT ROLE FLOWPROOF_RELAY_ROLE TO USER FLOWPROOF_RELAY;
GRANT USAGE ON WAREHOUSE FLOWPROOF_PILOT_WH TO ROLE FLOWPROOF_RELAY_ROLE;
GRANT USAGE ON DATABASE FLOWPROOF_PILOT TO ROLE FLOWPROOF_RELAY_ROLE;
GRANT USAGE ON SCHEMA FLOWPROOF_PILOT.RAW TO ROLE FLOWPROOF_RELAY_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE FLOWPROOF_PILOT.RAW.ORDERS TO ROLE FLOWPROOF_RELAY_ROLE;

CREATE TABLE IF NOT EXISTS FLOWPROOF_PILOT.RAW.FLOWPROOF_RELAY_TRANSACTIONS (
  transaction_id VARCHAR NOT NULL,
  source_xid NUMBER(38, 0) NOT NULL,
  commit_lsn VARCHAR NOT NULL,
  change_count NUMBER(38, 0) NOT NULL,
  committed_at TIMESTAMP_LTZ NOT NULL,
  merged_at TIMESTAMP_LTZ,
  PRIMARY KEY (transaction_id)
);

ALTER TABLE FLOWPROOF_PILOT.RAW.FLOWPROOF_RELAY_TRANSACTIONS
  ADD COLUMN IF NOT EXISTS merged_at TIMESTAMP_LTZ;

CREATE TABLE IF NOT EXISTS FLOWPROOF_PILOT.RAW.FLOWPROOF_OPENFLOW_SIM_JOURNAL (
  event_id VARCHAR NOT NULL,
  transaction_id VARCHAR NOT NULL,
  event_index NUMBER(38, 0) NOT NULL,
  source_schema VARCHAR NOT NULL,
  source_table VARCHAR NOT NULL,
  operation VARCHAR NOT NULL,
  primary_keys VARIANT NOT NULL,
  payload VARIANT,
  old_values VARIANT,
  commit_lsn VARCHAR NOT NULL,
  captured_at TIMESTAMP_LTZ NOT NULL,
  PRIMARY KEY (event_id)
);

GRANT SELECT, INSERT, UPDATE ON TABLE FLOWPROOF_PILOT.RAW.FLOWPROOF_RELAY_TRANSACTIONS TO ROLE FLOWPROOF_RELAY_ROLE;
GRANT SELECT, INSERT ON TABLE FLOWPROOF_PILOT.RAW.FLOWPROOF_OPENFLOW_SIM_JOURNAL TO ROLE FLOWPROOF_RELAY_ROLE;

ALTER WAREHOUSE FLOWPROOF_PILOT_WH SUSPEND;
